export interface User{
    id: string,
    user_detail_id: number,
    title: string,
    first_name: string,
    middle_name: string,
    last_name: string,
    fullName: string,
    email: string,
    country_prefix: string,
    phone_number: string,
    transfer_to_wallet: string,
    currency: any,
    email_verification: any,
    phone_verification: any,
    profile_picture:any,
    country: any,
    state: any,
    lga: any,
    ward: any,
    house_address: any,
    gender: any,
    marital_status: any,
    religion: any,
    nationality: any,
    date_of_birth: any
}